---
title: "Análise de dados"
output: html_notebook
---


```{r message=FALSE, warning=FALSE, include=FALSE}
require(tidyverse)
library(kableExtra)
require(vcd)
require(FactoMineR)
require(factoextra)
require(ca)
```


```{r}
d <- read_csv(
  "./processed/data_final.csv",
  col_types = cols(
    ID = col_double(),
    AUTHOR = col_character(),
    WORK = col_character(),
    LOCATION = col_character(),
    TEXT = col_character(),
    Vm = col_character(),
    VM_LEMMA = col_character(),
    VM_PERSONAL = col_logical(),
    VM_MOD = col_logical(),
    Vinf = col_character(),
    VINF_A = col_character(),
    VINF_B = col_character(),
    VINF_C = col_character(),
    VINF_D = col_character(),
    Vinf_Cop = col_logical(),
    Obj = col_character(),
    OBJ_A = col_character(),
    OBJ_B = col_character(),
    OBJ_C = col_character(),
    Pred = col_character(),
    PRED_A = col_character(),
    PRED_B = col_character(),
    PRED_C = col_character(),
    PRED_D = col_character(),
    PRED_E = col_character(),
    PRED_F = col_character(),
    PRED_G = col_character(),
    Attr = col_logical(),
    Attr_B = col_logical(),
    CHECK = col_logical(),
    Anot = col_character(),
    DIST_OBJ_PRED = col_double()
  )
)
d
```

### Proporção geral de atração

```{r}
table(d$Attr) %>%
  addmargins() %>%
  kable(col.names = c("Atração", "Freq"))
```
```{r}
prop.table(table(d$Attr)) %>%
  kable(col.names = c("Atração", "Prop"))
```

```{r}
p <- ggplot(d, aes(Attr)) +
  geom_bar(aes(fill = Attr), width = 0.7) +
  labs(
    x = "", y = "Contagem",
    fill = "Attraction"
  ) +
  theme(
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank()
  ) +
  scale_fill_brewer(palette = "Dark2")
b <- p + labs(title = "Contagem da atração de caso")
b
```

### Proporção atração e classe de verbo (A)

```{r}
table(d$VM_PERSONAL, d$Attr) %>%
  addmargins() %>%
  kable(
    col.names = c(
      "Vm Pessoal",
      "Sem atração",
      "Atração",
      "Soma"
    )
  )
```

```{r}
table(d$VM_PERSONAL, d$Attr) %>%
  prop.table(margin = 1) %>%
  kable(
    col.names = c(
      "Pessoal",
      "Sem atração",
      "Atração"
    )
  )
```

```{r}
table(d$VM_PERSONAL, d$Attr) %>% chisq.test()
```

```{r}
lables <- c("FALSE" = "Personal Vm = False", "TRUE" = "Personal Vm = True")
b <- p + facet_wrap(. ~ VM_PERSONAL, labeller = as_labeller(lables)) +
  labs(title = "Atração de caso Vm pessoal")
b
```

### Proporção atração e classe de verbo (B)

```{r}
table(d$VM_MOD, d$Attr) %>%
  addmargins() %>%
  kable(
    col.names = c(
      "Vm Modalizador",
      "Sem atração",
      "Atração",
      "Soma"
    )
  )
```

```{r}
table(d$VM_MOD, d$Attr) %>%
  prop.table(margin = 1) %>%
  kable(
    col.names = c(
      "Vm Modalizador",
      "Sem atração",
      "Atração"
    )
  )
```

```{r}
table(d$VM_MOD, d$Attr) %>% chisq.test()
```

```{r}
lables <- c(
  "FALSE" = "Vm modalizador = False",
  "TRUE" = "Vm modalizador = True"
)
b <- p + facet_wrap(. ~ VM_MOD, labeller = as_labeller(lables)) +
  labs(title = "Atração de caso e Vm modalizador")
b
```

### Proporção atração e cópula

```{r}
table(d$Vinf_Cop, d$Attr) %>%
  addmargins() %>%
  kable(
    col.names = c(
      "Vinf Copular",
      "Sem atração",
      "Atração",
      "Soma"
    )
  )
```

```{r}
table(d$Vinf_Cop, d$Attr) %>%
  prop.table(margin = 1) %>%
  kable(
    col.names = c(
      "Vinf Copular",
      "Sem atração",
      "Atração"
    )
  )
```

```{r}
table(d$Vinf_Cop, d$Attr) %>% chisq.test()
```

```{r}
lables <- c("FALSE" = "Copula = False", "TRUE" = "Copula = True")
b <- p + facet_wrap(. ~ Vinf_Cop, labeller = as_labeller(lables)) +
  labs(title = "Atração de caso e infinitivo copular")
b
```

### Autoria

```{r}
table(d$AUTHOR, d$Attr) %>%
  addmargins() %>%
  kable(
    col.names = c(
      "Autoria",
      "Sem atração",
      "Atração",
      "Soma"
    )
  )
```

```{r}
table(d$AUTHOR, d$Attr) %>%
  prop.table(margin = 1) %>%
  kable(
    col.names = c(
      "Autoria",
      "Sem atração",
      "Atração"
    )
  )
```

```{r}
table(d$AUTHOR, d$Attr) %>% chisq.test()
```

```{r}
ggplot(d, aes(y = AUTHOR)) +
  geom_bar(aes(fill = Attr)) +
  labs(
    x = "Contagem", y = "Autor",
    fill = "Atração"
  ) +
  theme(text = element_text(size = 12)) +
  scale_fill_brewer(palette = "Dark2")
```

### Atração e distância

```{r}
wilcox.test(d$DIST_OBJ_PRED ~ d$Attr, conf.int = TRUE)
```

```{r}
b <- ggplot(d, aes(Attr, DIST_OBJ_PRED, fill = Attr)) +
  geom_boxplot(outlier.shape = 15, outlier.size = 2.4) +
  labs(
    y = "Distância entre Obj e Pred",
    title = "Distância entre Obj e Pred em relação com a atração"
  ) +
  theme(
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank()
  ) +
  scale_fill_brewer(palette = "Dark2")
b
```

```{r}
mca <- MCA(
  d[,c(
    "Attr",
    "Vinf_Cop",
    "VM_MOD",
    "AUTHOR",
    "DIST_OBJ_PRED"
    )], 
  quali.sup = 4,
  quanti.sup = 5,
  method="Burt",
  graph = F)

fviz_screeplot(
  mca,
  addlabels = TRUE,
  ylim = c(0, 80),
  barfill="#1B9E77",
  barcolor="#1B9E77",
  main="Eigenvalues"
  ) + 
  theme_get()

mca.plot <- plot(
  mca,
  invisible = "ind",
  graph.type =  "ggplot"
  ) +
  theme_get()
mca.plot


```


```{r}
mca.b <- MCA(
  d[,c(
    "Attr",
    "Vinf_Cop",
    "VM_MOD",
    "AUTHOR",
    "DIST_OBJ_PRED"
    )], 
  quanti.sup = 5,
  method="Burt",
  graph = F)

fviz_screeplot(
  mca.b,
  addlabels = TRUE,
  barfill="#1B9E77",
  barcolor="#1B9E77",
  main="Eigenvalues"
  ) + 
  theme_get()

mca.plot <- plot(
  mca.b,
  invisible = "ind",
  graph.type =  "ggplot"
  ) +
  theme_get()
mca.plot
```